In [1]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 테스트
테스트


In [2]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [4]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [5]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [7]:
arVal[1][2]

3.14

In [8]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [9]:
arVal[0][2]

't'

In [10]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [13]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [14]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [15]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [16]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [18]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [19]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [20]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [21]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [22]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [23]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [24]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [25]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [30]:
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [31]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [32]:
pandas_series[0]

30

In [33]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [34]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [35]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [36]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [37]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [38]:
# DataFlame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [39]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [40]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [41]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [42]:
# column 삭제
del df['score']

In [43]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [47]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [48]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [51]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [55]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0 -0.271864 -0.574998  1.150394  0.646234 -1.872952
1 -2.716515 -0.397493 -1.715381 -1.370024 -0.649400
2  0.606620  0.789884 -0.419026 -1.185723 -1.942334
3 -0.539168 -0.849313 -0.956264 -0.126633  0.694226
4  1.425996 -0.177978  0.786634  0.620929 -0.086799

In [56]:
# 최대값
df.max()

A    1.425996
B    0.789884
C    1.150394
D    0.646234
E    0.694226
dtype: float64

In [58]:
# 최소값
df.min()

A   -2.716515
B   -0.849313
C   -1.715381
D   -1.370024
E   -1.942334
dtype: float64

In [60]:
# 평균
df.mean()

A   -0.298986
B   -0.241980
C   -0.230729
D   -0.283043
E   -0.771452
dtype: float64

In [61]:
# 표준편차
df.std()

A    1.557125
B    0.627052
C    1.194631
D    0.961970
E    1.141942
dtype: float64

In [62]:
# 누적값
df.cumsum()

A         B         C         D         E
0 -0.271864 -0.574998  1.150394  0.646234 -1.872952
1 -2.988379 -0.972491 -0.564987 -0.723790 -2.522353
2 -2.381758 -0.182607 -0.984013 -1.909513 -4.464686
3 -2.920926 -1.031920 -1.940276 -2.036146 -3.770460
4 -1.494930 -1.209898 -1.153643 -1.415217 -3.857260

In [63]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.298986 -0.241980 -0.230729 -0.283043 -0.771452
std    1.557125  0.627052  1.194631  0.961970  1.141942
min   -2.716515 -0.849313 -1.715381 -1.370024 -1.942334
25%   -0.539168 -0.574998 -0.956264 -1.185723 -1.872952
50%   -0.271864 -0.397493 -0.419026 -0.126633 -0.649400
75%    0.606620 -0.177978  0.786634  0.620929 -0.086799
max    1.425996  0.789884  1.150394  0.646234  0.694226

In [64]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.271864 -0.574998  1.150394  0.646234 -1.872952        X
1 -2.716515 -0.397493 -1.715381 -1.370024 -0.649400        Y
2  0.606620  0.789884 -0.419026 -1.185723 -1.942334        X
3 -0.539168 -0.849313 -0.956264 -0.126633  0.694226        Y
4  1.425996 -0.177978  0.786634  0.620929 -0.086799        Z

In [65]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         0.167378  0.107443  0.365684 -0.269745 -1.907643
Y        -1.627841 -0.623403 -1.335823 -0.748329  0.022413
Z         1.425996 -0.177978  0.786634  0.620929 -0.086799